CREATE TABLE IF NOT EXISTS DRCART.DRCART_USERS(
User_Id INT NOT NULL AUTO_INCREMENT,
User_Name VARCHAR(255) UNIQUE NOT NULL,
User_Email VARCHAR(255)  NOT NULL,
logged_time DATETIME NOT NULL,
login_password VARCHAR(255) NOT NULL,

PRIMARY KEY(User_Id,User_Email)
);