USE DRCART;
CREATE TABLE IF NOT EXISTS DRCART_USERS(
User_Id INT NOT NULL AUTO_INCREMENT,
User_Name VARCHAR(255) UNIQUE,
User_Email VARCHAR(255) ,
login_password VARCHAR(255),
PRIMARY KEY(User_Id,User_Email)
);