name: Node.js CI

on:
  push:
    branches:
      - main  # Test on push to the main branch
  pull_request:
    branches:
      - main  # Test on pull requests into the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Assuming Jest is used for tests


